### ISSUE TITLE
Lower AUROC results

### ISSUE THREAD

**Issue by Stexan** [georgeAccnt-GH/AzureChestXRayNoAML#1]
Hello @georgeAccnt-GH, and thank you very much for your implementation of the study! Our team has also tried to replicate your results, and while we have better results than the original poster, we still didn't reach your AUC (we have a mean of 0,81).

What happens is that around epoch 30-35, the algorithms starts overfitting, so training becomes useless as performance on the valid/test sets just drops. We have followed the exact same steps that you have implemented yourself.

Do you think the data splits have an impact and the difference might come from there? Or is there anything else you did specifically to make the network not overfit so fast (we have also tried random crops along with the augmentation techniques used in your implementation, but that didn't help much either)?

**Comment by georgeAccnt-GH** [comment]
Hi @Stexan 
Thank you for posting. For now the focus of this is just technology, i.e. showcasing multi-gpu training for deep learning in the Azure cloud. I will come back with more thorough data science process details. It is entirely possible a certain train-test split will get better results, but we should always report average results (plus top and bottom performance levels).  So your point is entirely valid. I hope I will have a more specific answer soon.
