### ISSUE TITLE
where is  blacklist.csv

### ISSUE THREAD

**Issue by chuijh** [georgeAccnt-GH/AzureChestXRayNoAML#2]
Where is the source of blacklist.csv? Is it created by you folks? Or is it created by the people at NIH?

Thanks,

**Comment by georgeAccnt-GH** [comment]
Thx for the feed-back. The missing files was added here:
https://github.com/georgeAccnt-GH/AzureChestXRayNoAML/blob/master/code/01_DataPrep/data/blacklist.csv

Yes, it was created by people with no medical expertise from MSFT. NIH was not involved in this.
